# -*- coding: utf-8 -*-
"""p201613104_5 jupyter notebook 변환

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13aSO408MQhGwYsBlu1vFCCt_hLsKs2bq
"""




'''
# 1. 1번 문제. 
# camille 이라는 이름의 dictionary를 생성하시오.

camille = {'health':576.6, 'health_regen':1.7, 'mana':338.8, 'mana_regen':1.63, 'melee':125, 'attack_damage':60}
print(camille)


# 1. 2번 문제 
# health 값을 580으로 변경하시오

camille['health'] = 580    # 'health' 변경
print(camille)


# 1. 3번 문제
# attack_speed 의 값을 0.625로 설정하고 추가하시오

camille['attack_speed'] = 0.625   # attack_speed 값 추가
print(camille)


# 1. 4번 문제 
# shen의 캐릭터 능력치를 제작하려 한다.
# mana regen, mana를 제거한다

shen = camille.copy()   # copy함수로 복사
del shen['mana_regen']  # mana regen 정보 제거
del shen['mana']   # mana 정보 제거
print(shen)
'''




'''
# 2번 문제. 
# 커피전문점의 메뉴 목록을 작성하는데, dictionary로 만드는 방법 4가지를 모두 사용해서 보여라


# 1번 방법(이 경우 공백을 '_'로 처리했다.)

Menu = dict(Americano = 2000, Cafe_latte = 2500, Green_Tea_latte = 3000, Mocha_latte = 3500)
print(Menu)


# 2번 방법

Menu = dict(zip(['Americano', 'Cafe latte', 'Green Tea latte', 'Mocha latte'], [2000, 2500, 3000, 3500]))
print(Menu)


# 3번 방법

Menu = dict([('Americano', 2000), ('Cafe latte', 2500), ('Green Tea latte', 3000), ('Mocha latte', 3500)])
print(Menu)


# 4번 방법

Menu = dict({'Americano':2000, 'Cafe latte':2500, 'Green Tea latte':3000, 'Mocha latte': 3500})
print(Menu)
'''





'''
# 문제 3번.
# list_a = [0, 1, 2, 3, 4, 5, 6, 7]이다.
# 다음 함수를 실행 했을 때 결과를 각각 확인하라.


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.extend(list_a)  # 리스트 확장
print(list_a)


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.append(10)  # 요소 10을 추가
print(list_a)


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.insert(3, 0)  # 인덱스 3 자리에 0을 추가
print(list_a)


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.remove(3)  # 요소 3을 제거
print(list_a)


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.pop(3)  # 요소 3을 제거
print(list_a)


list_a = [0, 1, 2, 3, 4, 5, 6, 7]
list_a.clear()  # 요소를 모두 지운다.
print(list_a)
'''





'''
# 4.1번 
# 슬라이싱 연산을 사용하여 하나의 리스트에 다른 리스트값을 추가하라.

a = [1, 2]    # 원본 
print('원본 : ', a)

a[2:0] = [3, 4, 5]    # 슬라이싱으로 추가
print('결과 : ', a)



# 4.2번
# 리스트 메소드(함수)를 이용하여 추가하라.

a = [1, 2]    # 원본
print('원본 : ', a)

a.extend([3, 4, 5])    # 메소드로 추가
print('결과 : ', a)
'''





'''
# 5. 1번
# 딕셔너리에 (홈런볼 : 900, 콘치즈 : 1050) 을 추가하라.

snacks = {'새우깡' : 700, '꼬깔콘' : 750, '오징어땅콩' : 1000}
print(snacks)   # 원래 가격 딕셔너리

snacks.setdefault('홈런볼', 900)
snacks.setdefault('콘치즈', 1050)

print(snacks)   # 추가된 딕셔너리



# 5. 2번
# 콘치즈 정보를 삭제하고, 콘치라는 새로운 정보를 추가하라. 콘치 : 1350

snacks.pop('콘치즈')    # 콘치즈 정보 삭제
print(snacks)

snacks.setdefault('콘치', 1350)    # 콘치 정보 추가
print(snacks)



# 5. 3번 
# 딕셔너리의 키 만 출력하시오.
print(snacks.keys())


# 5. 4번 
# 딕셔너리의 값 만 출력하시오.
print(snacks.values())
'''





'''
# 6번 문제.
# 표준입력으로 문자열 여러개와 숫자 여러개가 두 줄로 입력되고,
# 첫 번째 줄은 키, 두 번째 줄은 값을 입력하여 딕셔너리를 생성하시오.

keys = []
keys = input("키값 입력 : ").split()  # 표준입력으로 문자열 여러개 입력받음

values = []
values = map(int, input("숫자 값 입력 : ").split())   # 표준입력으로 숫자 여러개 입력 받음


list_a = dict(zip(keys, values))  # 키와 밸류 리스트를 zip함수로 묶고, dict함수로 처리한다.

print(list_a)
'''





