# -*- coding: utf-8 -*-
"""프로그래밍 7주차 실습 과제 (Jupyter notebook 변환)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M2Rix7d3gBTvDQo4QI8bsqADUYDzB1Gt
"""





'''
# 1번
# 반복문을 사용하여 별 모양 출력하기

# 각 지점의 위치를 (i, j)라고 할 때, 
# i <= j인 지점에서만 별이 찍히면 된다.

N = 5
for i in range(N):
    for j in range(N):

        if i <= j: 
            print('*', end='')
        else:
            print(" ", end='')

    print() # 자동줄바꿈

# 교수님. 1번 문제의 별 그림에서 별 사이의 공백이 있는건지 없는건지 헷갈려서,
# 주석 남깁니다.
# 문제에 나온 그림에서 만약 별들 사이의 공백이 있는 것이라면,
# if, else 절에서 각각 end=' '로 공백을 추가해주면 된다고 봅니다.
'''




'''
# 2번
# 학급에 총 10명의 학생이 있고, 이들의 중간고사 점수는 다음과 같다.
# 반복문을 사용하여 학급의 평균점수 구하기
# for문으로 각 학생의 점수를 꺼내서 더해나가고, 학생수로 나눠 평균을 구한다.

score = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

average = 0  # 평균점수 초기값 설정
for i in score :
    average += i / len(score) # 평균 계산, 나누기를 미리 해주며 더한다. 

print(average)
'''





'''
# 3.1 번

# 2이상, 100미만의 정수 중에서 
# 2로도 안나눠지고, 3으로도 안나눠지는 수 찾아서 출력하기
# while 루프 + continue문 사용해서 작성하기

i = 2  # 초기식

while i < 100 :  # 조건식
    
    i = i + 1  # 변화식 
    
    if i%2 == 0 or i%3 == 0:  # 2의 배수이거나, 3의 배수이면
        continue    # 밑의 코드를 실행안하고 넘어간다.
        
    print(i, end=' ') # 나눠지지 않는 그 수를 출력한다.
'''





'''
# 3.2 번
# 이번에는 continue문 사용하지 않은 방식으로 작성하기

i = 2  # 초기식

while i < 100 :  # 조건식
    
    if i%2 != 0 and i%3 != 0: # 2로도 안나눠지고, 3으로도 안나눠지는 수
        
        print(i, end=' ') # 그 수를 출력한다.
        
    i = i + 1  # 변화식
'''







'''
# 4.1 번 
# 2단부터 9단까지 구구단을 출력하는 프로그램을 작성해보자(중첩 반복)

# for문 이용해서 작성하기

for i in range(2, 10): # 2단부터 9단까지
    
    print(str(i)+' 단 : ', end = ' ')
    
    for j in range(1, 10): # 곱하기1부터 곱하기9까지
        
        print(i * j, end =' ')
    print() # 자동줄바꿈
'''






'''
# 4.2 번 
# while문 이용해서 구구단 코드 작성하기 

i = 2  # 초기값

while i < 10 :  # i 조건식
    
    j = 1  # 내부에서 새로운 j 초기값
    
    print(str(i) + ' 단 : ', end =' ')  # 단 출력
    
    while j < 10 :  # j 조건식
        print(i * j, end=' ')
        j = j + 1  # j 변화식
        
    print()   # 자동줄바꿈
    
    i = i + 1  # i 변화식 
'''








'''
# 5번. FizzBuzz 문제

# 1에서 100까지 출력한다. 
# 3의 배수는 Fizz 출력
# 5의 배수는 Buzz 출력
# 3과 5의 공배수는 FizzBuzz 출력
# 10의 자리마다 줄바꿈


for i in range(1, 101):   # 1부터 100까지의 정수에 대하여... 
    
    if i % 30 == 0:  # 15의 공배수이면서, 줄바꿈해야 함
        print("FizzBuzz")  
        
    elif i % 10 == 0:  # 5의 배수이면서, 줄바꿈해야 함
        print("Buzz")
        
    elif i % 3 == 0 and i % 5 == 0 :   # 3과 5의 공배수이면 
        print("FizzBuzz", end=' ') 
    
    elif i % 3 == 0:   # 3의 배수이면
        print("Fizz", end =' ')
        
    elif i % 5 == 0:  # 5의 배수이면
        print("Buzz", end =' ')
        
    else:  # 아무것도 아니면 그냥 해당 수 출력
        print(i, end=' ')
'''






'''
# 6번
# 표준 입력으로 삼각형의 높이를 입력받고, 입력된 높이만큼 산 모양의 별 출력하기

# 별은 중앙대칭적으로 배열되어야 한다.
# 별은 줄이 늘어날때마다 2개씩 늘어난다--> 홀수 (2n - 1)개
# 별의 좌우에는 공백 배치한다. 
# reversed 함수 이용하여 좌, 우 배치를 각각 출력하여 더한다.

N = int(input("높이를 입력하세요 : "))

for i in range(N):  # 가로줄
     
    for j in reversed(range(N)):  # 별 모양의 절반 부분
        if j > i:
            print(' ', end='')
        else: 
            print('*', end='')
            
    for j in range(N): # 별 모양의 다른 절반 부분
        if j < i:
            print('*', end='')
    print() # 자동 줄바꿈

# 교수님. 파이썬 IDLE에서는 약간 비스듬히 나오고
# 파이참에서는 깔끔하게 별 모양이 출력됩니다.
'''




